### ISSUE TITLE
small issue with string tests

### ISSUE THREAD

**Issue by zkat** [bgotink/kdl#6]
This is not quite right: https://github.com/bgotink/kdl/blob/f66084b155b0de3ebc438f02801d55cebcd660f1/test/string.js#L13-L32

The opening and closing `"` need to be aligned with each other in order for this to test what it seems to be trying to test. But they're off-by-one.

**Comment by bgotink** [comment]
They're indeed indented weirdly, but the indentation of the opening quote doesn't matter, does it?
The indentation to remove is purely defined by the closing quote, the opening quote the newline immediately after it are stripped and don't have any further significance.

I've updated the test to

```js
parse(String.raw`
		node "
			foo \
			bar
			baz
			"
`);

assert.throws(() => {
	parse(String.raw`
		node "
			foo \
		bar
			baz
			"
	`);
});
```

to ensure the test only succeeds because of the invalid indentation of the `bar` line.

**Comment by zkat** [comment]
facepalm. I ran into this when I was implementing things myself recently, and I forgot to close this. You're right: the location of the opening `"` doesn't matter.
